### ISSUE TITLE
java.lang.Exception: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [mychannel] creator org [org1MSP]

### ISSUE THREAD

**Issue by mk0214** [ecsoya/fabric-demo#5]
2020-04-05 16:34:24.488 ERROR 19054 --- [  restartedMain] org.hyperledger.fabric.sdk.Channel       : Channel Channel{id: 1, name: mychannel} Sending proposal with transaction: 0b465cacd0fc1af328a6f4edceac8c9a7df32c27e52a1b1b9d9ff27b59af8261 to Peer{ id: 4, name: peer1.org1.example.com, channelName: mychannel, url: grpcs://127.0.0.1:8051, mspid: org1MSP} failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [org1MSP], cause=null}

java.lang.Exception: io.grpc.StatusRuntimeException: UNKNOWN: access denied: channel [mychannel] creator org [org1MSP]
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4525) [fabric-sdk-java-1.4.6.jar:na]
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:952) [fabric-sdk-java-1.4.6.jar:na]
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:918) [fabric-sdk-java-1.4.6.jar:na]
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:2045) [fabric-sdk-java-1.4.6.jar:na]
	at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1882) [fabric-sdk-java-1.4.6.jar:na]
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1267) [fabric-sdk-java-1.4.6.jar:na]
大佬，这个发送交易失败了是怎么回事啊。

**Comment by cayden** [comment]
问题解决了吗？你可以试试端口是否OK?

**Comment by jay61439476** [comment]
问题解决了吗？
我的是类似错误
`java.lang.Exception: io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closed while performing protocol negotiation for [HttpClientCodec#0, HttpProxyHandler#0, ProtocolNegotiators$WaitUntilActiveHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]`

**Comment by yanzhi516** [comment]
同问，问题解决了没？

**Comment by yanzhi516** [comment]
解决了！需要修改一下，把Org1MSP （注意大小写） 改成 org1MSP 就行了
